### ISSUE TITLE
Spinning problem

### ISSUE THREAD

**Issue by mado-bohsali** [kevlatus/flutter_fortune_wheel#34]
Please note that I need your clarification on fling property as well as physics. Notice that the wheel isn't in the centre of the screen hence => onAnimationEnd is giving wrong values

![Simulator Screen Shot - iPhone 11 - 2021-03-04 at 22 16 23](https://user-images.githubusercontent.com/18421260/110024946-6f5d7080-7d37-11eb-867b-fbb1c2731b28.png)

**Comment by kevlatus** [comment]
thanks for reaching out @mado-bohsali!
I haven't tested the wheel with right-to-left layouts, so I wasn't aware of this behavior. v0.4.2 will be published in a few minutes and includes a fix for the centering issue.

Unfortunately, I do not understand how this affects `onAnimationEnd`, since the animation callback is independent from the positioning. If you still experience issues, please open a new issue with a reproducible example.
